

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: trabajito
      POSTGRES_PASSWORD: trabajito
      POSTGRES_DB: trabajito_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"

